---
title: Housi
timezone: UTC
collections:
  footer:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
permalink: "/blog/:title"
tagline: blog
description: My personal blog.
url: http://housi.co
baseurl: /
commentsystem: google
disqus: example
author:
  name: Brendan Johnson
paginate: 5
icon: "/assets/images/logo.png"
cover: "/assets/images/bg.png"
social:
- icon: twitter
  url: https://twitter.com/
  desc: Follow us on twitter
- icon: instagram
  url: https://instagram.com/
  desc: Follow us on instagram
- icon: facebook
  url: https://facebook.com/
  desc: Follow us on facebook
menu:
- title: Home
  url: "/"
- title: About
  url: "/about"
copyright:
  author: Camporez
  url: http://camporez.github.io
  type_title: Some rights reserved
  type_url: http://creativecommons.org/licenses/by-nc/2.5
parallax: false
google_analytics: 
theme_color: 7E9576
